config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    get 'fund',    on: :member
    get 'retired', on: :collection
  end
  resources :households do
    post 'fund', on: :member
  end
  resources :notes
  resources :recurrings
  resources :reports
  resources :sessions
  resources :tags
  resources :things
  resources :transactions
  resources :users do
    post 'recur', on: :member
  end
  resources :vendors
  resources :weights
  resources :workouts

  get 'date/:year/:month/:day'=>'date#show', as: 'date'

  get 'graphs/health/:start/:finish.:format'=>'graphs#health', as: 'health'
  get 'graphs/spending/:start/:finish.:format'=>'graphs#spending', as: 'spending'

  root to: 'things#index'

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  def index
    @things = Current.user.things_during((Time.zone.now.to_date - 4)..Time.zone.now.to_date)
    @month  = (Time.zone.today - 30)..Time.zone.today

    # Preload data for spending graph to avoid N+1 queries
    month_start = @month.first - 1.month
    transactions = Current.household.transactions
                          .includes(:debit, :credit)
                          .where(transactions: { date: month_start..@month.last })
                          .where(exceptional: false)
                          .to_a

    # Calculate cumulative expenses for each day
    @expense_data = @month.map do |date|
      transactions
        .select { |t| t.date.between?(@month.first, date) && t.debit&.ledger == 'expense' }
        .sum(&:amount)
    end

    # Calculate cumulative income for each day
    @income_data = @month.map do |date|
      transactions
        .select { |t| t.date.between?(@month.first, date) && t.credit&.ledger == 'income' }
        .sum(&:amount)
    end

    # Preload workouts for workout graph
    workouts = Current.user.workouts.during(@month).to_a
    @workout_data = @month.map do |date|
      workouts.select { |w| w.date == date }.sum(&:minutes)
    end

    # Preload weights for health graph
    weights = Current.user.weights.during(@month).to_a
    @weight_data = @month.map do |date|
      weight = weights.find { |w| w.date == date }
      weight ? weight.weight.to_f : nil
    end

    # Check if we have health data
    @has_health_data = workouts.any? || weights.any?

    # Preload dashboard accounts with their balances computed in SQL
    @dashboard_accounts = Current.household.accounts.dashboard.with_balances.to_a
    @budget_categories = @dashboard_accounts.map { |a| a.name.gsub(' Deferral', '') }
    @budget_balances = @dashboard_accounts.map do |account|
      amount = account.balance
      { y: amount, color: (amount.negative? ? '#FF00CC' : '#00CCFF') }
    end
  end

  def new
    render layout: false
  end

  def create
    @thing = Grammar.parse params[:thing], Current.user
    @thing.user = Current.user
    @thing.save!
    redirect_to root_url
  end

end

app/views/things/_thing.html.haml
= cache thing do
  - if thing.is_a?(Transaction)

    - if thing.secret? && thing.user_id.presence != Current.user.id
      %tr.transaction
        %td.date
          &nbsp;
          = link_to thing.date, date_link(thing.date)
        %td{colspan: 2}
          %span.secret SECRET
    - else
      %tr.transaction
        %td.date
          = link_to '«', thing, data: { turbo_frame: 'modal' }
          = link_to thing.date, date_link(thing.date)
        %td
          = vendor_name thing
          = thing.description.presence
          %span.tags= linked_tag_list thing
          - if thing.secret?
            %span.secret SECRET
        %td.debit
          - if thing.debit
            = link_to thing.debit.name, thing.debit, class: 'debit'
          - else
            FIX ME!!!
        %td.credit
          - if thing.credit
            = link_to thing.credit.name, thing.credit, class: 'credit'
          - else
            FIX ME !!!
        %td.money
          = number_to_currency thing.amount, precision: 0

  - elsif thing.is_a?(Note)
    %tr
      %td.date
        = link_to '«', thing, data: { turbo_frame: 'modal' }
        = link_to thing.date, date_link(thing.date)
      %td{colspan: 4}
        - if thing.body.length < 80
          = thing.body
        - else
          .preview #{thing.body.first(80)} #{link_to '...', '', class: 'expand_note'}
          .hide= simple_format thing.body

  - elsif thing.is_a?(Weight)
    %tr
      %td.date
        = link_to '«', thing, data: { turbo_frame: 'modal' }
        = link_to thing.date, date_link(thing.date)
      %td{colspan: 4} Weight #{thing.weight}lbs

  - elsif thing.is_a?(Workout)
    %tr
      %td.date
        = link_to '«', thing, data: { turbo_frame: 'modal' }
        = link_to thing.date, date_link(thing.date)
      %td{colspan: 4}= thing

app/views/things/_things.html.haml
- unless things.empty?
  %table
    %tr
      %th Date
      %th
      %th Debit
      %th Credit
      %th Amount

    %tbody
      - things.each do |thing|
        = render 'things/thing', thing: thing

app/views/things/index.html.haml
-# = turbo_stream_from Current.household
-# = turbo_stream_from Current.user

= form_with path: things_path do
  = text_field_tag 'thing', '', class: 'long', autofocus: true
- if Current.user.recurrings.on(Time.zone.today).any? && Current.user.transactions.on(Time.zone.today).none?
  = button_to '+ Add Daily Recurring', [:recur, Current.user], method: :post, data: { turbo: false }
- if [1, 15].include?(Time.zone.today.mday) && Current.household.transactions.on(Time.zone.today).where(recurring: nil).none?
  = button_to '+ Fund Accounts', [:fund, Current.household], method: :post, data: { turbo: false }

#Graphs
  = cache [Current.household, :spending] do
    #SpendingMonth{
      data: {
        controller: 'spending-graph',
        spending_graph_expense_value: @expense_data.to_json,
        spending_graph_income_value: @income_data.to_json,
        spending_graph_start_year_value: (@month.first - 1.month).year,
        spending_graph_start_month_value: (@month.first - 1.month).month,
        spending_graph_start_day_value: (@month.first - 1.month).day
      }
    }

  = cache [Current.user, :health] do
    - if @has_health_data
      #HealthMonth{
        data: {
          controller: 'health-month',
          health_month_workout_value: @workout_data.to_json,
          health_month_weights_value: @weight_data.to_json,
          health_month_start_year_value: (@month.first - 1.month).year,
          health_month_start_month_value: (@month.first - 1.month).month,
          health_month_start_day_value: (@month.first - 1.month).day
        }
      }
.clear

= cache [Current.household, :budget] do
  #BudgetMonth{
    data: {
      controller: 'budget-month',
      budget_month_categories_value: @budget_categories,
      budget_month_balances_value: @budget_balances.to_json
    }
  }

= cache [Current.household, :totals] do
  %h3
    = link_to 'This Year', '#'
    = color_money(Current.household.sum_non_exceptional_expenses(1.year.ago..Time.zone.today) * -1)

  %h3
    = link_to 'Cash', accounts_path
    = color_money Current.household.checking_plus_earmarks

  %h3
    = link_to 'Credit Card', accounts_path
    = color_money Current.household.credit_card.balance

= render partial: 'things', object: @things

app/views/things/new.haml
= modal do
  = form_with path: things_path, data: { turbo: false } do
    %p= text_area_tag 'thing', ''
    %p= submit_tag 'Save'

app/views/things/new.html.haml
= modal do
  = form_with path: things_path, data: { turbo: false } do
    %p= text_area_tag 'thing', ''
    %p= submit_tag 'Save'