config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    get 'fund',    on: :member
    get 'retired', on: :collection
  end
  resources :households do
    post 'fund', on: :member
  end
  resources :notes
  resources :recurrings
  resources :reports
  resources :sessions
  resources :tags
  resources :things
  resources :transactions
  resources :users do
    post 'recur', on: :member
  end
  resources :vendors
  resources :weights
  resources :workouts

  get 'date/:year/:month/:day'=>'date#show', as: 'date'

  get 'graphs/health/:start/:finish.:format'=>'graphs#health', as: 'health'
  get 'graphs/spending/:start/:finish.:format'=>'graphs#spending', as: 'spending'

  root to: 'things#index'

end

app/models/tag.rb
class Tag < ApplicationRecord
  include Permalink

  scope :visible_by, ->(user){
    where("transactions.created_at >= ? AND (transactions.secret = ? OR transactions.user_id = ?)", user.created_at, false, user.id)
  }

  validates :name, presence: true, uniqueness: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # GET /tags
  def index
    @tags = Current.household.tags.visible_by(Current.user).page params[:page]

    # Precompute transaction counts and sums for all tags to avoid N queries
    tag_ids = @tags.map(&:id)
    @tag_stats = Current.household.transactions.visible_by(Current.user)
      .joins(:taggings)
      .where(taggings: { tag_id: tag_ids })
      .group('taggings.tag_id')
      .select('taggings.tag_id, COUNT(*) as transaction_count, SUM(amount) as total_amount')
      .index_by(&:tag_id)
  end

  # GET /tags/:id
  def show
    @tag = Tag.find_by!(permalink: params[:id])
    @transactions = Current.household.transactions.tagged_with(@tag).visible_by(Current.user)
      .includes(:vendor, :tags, :debit, :credit, :user)
      .order(date: :desc)
      .page(params[:page])
  end

end

app/views/tags/_graph.erb
<script type='text/javascript'>
  $(document).ready(function(){
    healthMonth = new Highcharts.Chart({
      chart: {
        renderTo: 'TagGraph'
      },
      title:  { text: false },
      legend: { enabled: false },
      yAxis: {
        title: false
      },
      xAxis: {
        type: 'datetime',
        tickInterval: 30 * 24 * 3600 * 1000,
        labels: {
          step: 1,
          formatter: function(){
            return(Highcharts.dateFormat('%B',this.value));
          }
        }
      },
      series: [{
        type: 'column',
        name: 'Spending',
        data: <%= @user.tag_json @period, @tag %>,
        pointInterval: 30 * 24 * 3600 * 1000,
        pointStart: Date.UTC(2007, 1, 1),
        color: '#00CCFF'
      }]
    });
  });
</script>

app/views/tags/_graph.html.erb
<script type='text/javascript'>
  $(document).ready(function(){
    healthMonth = new Highcharts.Chart({
      chart: {
        renderTo: 'TagGraph'
      },
      title:  { text: false },
      legend: { enabled: false },
      yAxis: {
        title: false
      },
      xAxis: {
        type: 'datetime',
        tickInterval: 30 * 24 * 3600 * 1000,
        labels: {
          step: 1,
          formatter: function(){
            return(Highcharts.dateFormat('%B',this.value));
          }
        }
      },
      series: [{
        type: 'column',
        name: 'Spending',
        data: <%= Current.user.tag_json @period, @tag %>,
        pointInterval: 30 * 24 * 3600 * 1000,
        pointStart: Date.UTC(2007, 1, 1),
        color: '#00CCFF'
      }]
    });
  });
</script>

app/views/tags/_tags.haml
%table
  %tr
    %th Name
    %th Count
    %th Spent

  %tbody
    - tags.each do |tag|
      %tr
        %td= link_to tag.name, tag_path(tag)
        %td.num= number_with_delimiter @household.transactions.visible_by(@user).tagged_with(tag).count
        %td.num= number_to_currency @household.transactions.visible_by(@user).tagged_with(tag).sum(:amount), precision: 0

app/views/tags/_tags.html.haml
%table
  %tr
    %th Name
    %th Count
    %th Spent

  %tbody
    - tags.each do |tag|
      - stats = @tag_stats[tag.id]
      %tr
        %td= link_to tag.name, tag_path(tag)
        %td.num= stats ? number_with_delimiter(stats.transaction_count) : 0
        %td.num= stats ? number_to_currency(stats.total_amount, precision: 0) : number_to_currency(0, precision: 0)

app/views/tags/index.haml
%h1 Tags

= render partial: 'tags', object: @tags

= will_paginate @tags

app/views/tags/index.html.haml
%h1 Tags

= render partial: 'tags', object: @tags

= will_paginate @tags

app/views/tags/show.haml
%h1= @tag.name.titleize

%h3
  Total
  = color_money(@transactions.sum(:amount))

= render partial: 'things/things', object: @transactions

= will_paginate @transactions

app/views/tags/show.html.haml
%h1= @tag.name.titleize

%h3
  Total
  = color_money(@transactions.sum(:amount))

= render partial: 'things/things', object: @transactions

= will_paginate @transactions