config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    get 'fund',    on: :member
    get 'retired', on: :collection
  end
  resources :households do
    post 'fund', on: :member
  end
  resources :notes
  resources :recurrings
  resources :reports
  resources :sessions
  resources :tags
  resources :things
  resources :transactions
  resources :users do
    post 'recur', on: :member
  end
  resources :vendors
  resources :weights
  resources :workouts

  get 'date/:year/:month/:day'=>'date#show', as: 'date'

  get 'graphs/health/:start/:finish.:format'=>'graphs#health', as: 'health'
  get 'graphs/spending/:start/:finish.:format'=>'graphs#spending', as: 'spending'

  root to: 'things#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  # GET /transactions
  def index
    if params[:date]
      year  = params[:date][:year]  ? params[:date][:year].to_i  : Time.zone.today.year
      month = params[:date][:month] ? params[:date][:month].to_i : Time.zone.today.month
    else
      year  = Time.zone.today.year
      month = Time.zone.today.month
    end

    @period = Date.new(year, month, 1)..Date.civil(year, month, -1)

    if @period.first < Current.user.created_at.to_date
      @period = Current.user.created_at.beginning_of_month.to_date..Current.user.created_at.end_of_month.to_date
    end

    @transactions = Current.household.transactions.during(@period).includes(:vendor, :tags, :debit, :credit, :user)
  end

  # GET /transactions/:id
  def show
    @transaction = Current.household.transactions.find params[:id]
    render layout: false
  end

  # POST /transactions/:id
  def create
    @transaction = Current.household.transactions.build transaction_params
    @transaction.user = Current.user
    @transaction.save
    redirect_back_or @transaction.credit
  end

  # PUT /transactions/:id
  def update
    @transaction = Current.household.transactions.find params[:id]
    @transaction.update! transaction_params
    redirect_back_or root_url
  end

  # DELETE /transaction/:id
  def destroy
    @transaction = Current.household.transactions.find params[:id]
    @transaction.destroy
    redirect_back_or root_url
  end

  protected
  def transaction_params
    params.expect(transaction: [:amount, :credit_id, :date, :debit_id, :description, :exceptional, :tag_list, :secret, :vendor_name])
  end

end

app/views/transactions/index.haml
%h1= humanize_period @period

.date_selector
  = form_tag transactions_path, method: :get do
    = select_month @period.first
    = select_year  @period.first, start_year: @user.created_at.year, end_year: Time.zone.today.year
    = submit_tag 'Change'
.clear

- if @transactions.empty?
  %p No Activity
- else
  = render partial: 'things/things', object: @transactions

.date_selector
  = form_tag transactions_path, method: :get do
    = select_month @period.first
    = select_year  @period.first, start_year: @user.created_at.year, end_year: Time.zone.today.year
.clear

app/views/transactions/index.html.haml
%h1= humanize_period @period

.date_selector
  = form_tag transactions_path, method: :get do
    = select_month @period.first
    = select_year  @period.first, start_year: Current.user.created_at.year, end_year: Time.zone.today.year
    = submit_tag 'Change'
.clear

- if @transactions.empty?
  %p No Activity
- else
  = render partial: 'things/things', object: @transactions

.date_selector
  = form_tag transactions_path, method: :get do
    = select_month @period.first
    = select_year  @period.first, start_year: Current.user.created_at.year, end_year: Time.zone.today.year
.clear

app/views/transactions/show.haml
= modal do

  %h1 Edit Transaction

  %p Added by #{@transaction.user.name}

  = form_with model: @transaction, data: { remote: true, turbo: false } do |f|
    %p= f.date_select :date,          order: [:month, :day, :year]
    %p Amount
    %p= f.text_field :amount,        class: 'money'
    %p Vendor
    %p= f.text_field :vendor_name, default: 'vendor'
    %p Description
    %p= f.text_field :description, default: 'description'
    %p Tags
    %p= f.text_field :tag_list,    default: 'tags'

    %p
      = f.check_box :secret
      = f.label :secret, 'Top Secret'

    %p
      = f.check_box :exceptional
      = f.label :exceptional, 'Exceptional'

    %p
      Debit:
      = f.collection_select :debit_id, @household.accounts.active, :id, :name, include_blank: true
    %p
      Credit:
      = f.collection_select :credit_id, @household.accounts.active, :id, :name, include_blank: true
    %p
      = submit_tag 'Update'
      or

  %span.delete= button_to 'delete', @transaction, method: :delete, data: { turbo: false }

app/views/transactions/show.html.haml
= modal do

  %h1 Edit Transaction

  %p Added by #{@transaction.user.name}

  = form_with model: @transaction, data: { remote: true, turbo: false } do |f|
    %p= f.date_select :date,          order: [:month, :day, :year]
    %p Amount
    %p= f.text_field :amount,        class: 'money'
    %p Vendor
    %p= f.text_field :vendor_name, default: 'vendor'
    %p Description
    %p= f.text_field :description, default: 'description'
    %p Tags
    %p= f.text_field :tag_list,    default: 'tags'

    %p
      = f.check_box :secret
      = f.label :secret, 'Top Secret'

    %p
      = f.check_box :exceptional
      = f.label :exceptional, 'Exceptional'

    %p
      Debit:
      = f.collection_select :debit_id, Current.household.accounts.active, :id, :name, include_blank: true
    %p
      Credit:
      = f.collection_select :credit_id, Current.household.accounts.active, :id, :name, include_blank: true
    %p
      = submit_tag 'Update'
      or

  %span.delete= button_to 'delete', @transaction, method: :delete, data: { turbo: false }