config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    get 'fund',    on: :member
    get 'retired', on: :collection
  end
  resources :households do
    post 'fund', on: :member
  end
  resources :notes
  resources :recurrings
  resources :reports
  resources :sessions
  resources :tags
  resources :things
  resources :transactions
  resources :users do
    post 'recur', on: :member
  end
  resources :vendors
  resources :weights
  resources :workouts

  get 'date/:year/:month/:day'=>'date#show', as: 'date'

  get 'graphs/health/:start/:finish.:format'=>'graphs#health', as: 'health'
  get 'graphs/spending/:start/:finish.:format'=>'graphs#spending', as: 'spending'

  root to: 'things#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  # GET /reports
  def index
    set_period

    @income = Current.household.sum_income @period
    @exceptional_income = Current.household.sum_non_exceptional_income @period, Current.household.checking

    @expenses = Current.household.sum_expenses(@period) * -1
    @exceptional_expenses = Current.household.sum_non_exceptional_expenses(@period) * -1

    @net = @income + @expenses
    @exceptional_net = @exceptional_income + @exceptional_expenses

    @duration = (@finish - @start + 1).to_i

    @expense_accounts = Current.household.expense_accounts.where(transactions: { date: @period })
    @expense_tags     = Tag
      .joins("INNER JOIN taggings ON tags.id = taggings.tag_id AND taggings.taggable_type = 'Transaction'")
      .joins('INNER JOIN transactions ON taggings.taggable_id = transactions.id')
      .joins('INNER JOIN accounts ON transactions.debit_id = accounts.id')
      .where(transactions: { household_id: Current.household.id, date: @period })
      .where('accounts.ledger = ?', Account.ledgers[:expense])
      .select('tags.*, COUNT(transactions.debit_id) AS transaction_count, SUM(transactions.amount) AS total')
      .group('tags.id')
      .order(total: :desc)

    # Create lookup hashes for non-exceptional totals
    @non_exceptional_account_totals = Current.household.transactions
      .where(date: @period, exceptional: false)
      .joins('INNER JOIN accounts ON transactions.debit_id = accounts.id')
      .where('accounts.ledger = ?', Account.ledgers[:expense])
      .group('accounts.id')
      .sum(:amount)

    @non_exceptional_tag_totals = Current.household.transactions
      .where(date: @period, exceptional: false)
      .joins("INNER JOIN taggings ON transactions.id = taggings.taggable_id AND taggings.taggable_type = 'Transaction'")
      .joins('INNER JOIN accounts ON transactions.debit_id = accounts.id')
      .where('accounts.ledger = ?', Account.ledgers[:expense])
      .group('taggings.tag_id')
      .sum(:amount)
  end

end

app/views/reports/index.haml
%h1= humanize_period @period

= form_tag reports_path, method: :get do
  = select_month @start, prefix: 'start'
  = select_day   @start, prefix: 'start'
  = select_year  @start, prefix: 'start', start_year: @user.created_at.year, end_year: Time.zone.today.year
  &mdash;
  = select_month @finish, prefix: 'finish'
  = select_day   @finish, prefix: 'finish'
  = select_year  @finish, prefix: 'finish', start_year: @user.created_at.year, end_year: Time.zone.today.year
  = submit_tag 'Go'

#SpendingYear{ data: {
  controller: 'spending-graph',
  spending_graph_expense_value: @period.step(7).collect{|date| @household.sum_expenses(@period.first..date) * -1},
  spending_graph_income_value: @period.step(7).collect{|date| @household.sum_income @period.first..date},
  spending_graph_start_year_value: (@period.first - 1.month).year,
  spending_graph_start_month_value: (@period.first - 1.month).month,
  spending_graph_start_day_value: (@period.first - 1.month).day
}}

%table
  %tr
    %td{colspan: 2} All
  %tr
    %td Income
    %td= color_money @income
  %tr
    %td Expenses
    %td= color_money @expenses
  %tr
    %td Net
    %td= color_money @net
  - unless @income.zero?
    %tr
      %td Savings Rate
      %td #{(@net / @income.to_f * 100).round(1)}%

  %tr
    %td{colspan: 2} Non-Exceptional Cash
    %tr
      %td Income
      %td= color_money @exceptional_income
    %tr
      %td Expenses
      %td= color_money @exceptional_expenses
    %tr
      %td Net
      %td= color_money @exceptional_net
    - unless @exceptional_income.zero?
      %tr
        %td Savings Rate
        %td #{(@exceptional_net / @exceptional_income.to_f * 100).round(1)}%

%h2 Top Expenses
%table
  %tr
    %th Account
    %th Transactions
    %th Total
  - @expense_accounts.each do |account|
    %tr
      %td= account.name
      %td.count= account.transaction_count
      %td.count= color_money(account.total * -1)


%table
  %tr
    %th Account
    %th Transactions
    %th Total
  - @expense_tags.each do |tag|
    %tr
      %td= tag.name
      %td.count= tag.transaction_count
      %td.count= color_money(tag.total * -1)

app/views/reports/index.html.haml
%h1= humanize_period @period

= form_tag reports_path, method: :get do
  = select_month @start, prefix: 'start'
  = select_day   @start, prefix: 'start'
  = select_year  @start, prefix: 'start', start_year: Current.user.created_at.year, end_year: Time.zone.today.year
  &mdash;
  = select_month @finish, prefix: 'finish'
  = select_day   @finish, prefix: 'finish'
  = select_year  @finish, prefix: 'finish', start_year: Current.user.created_at.year, end_year: Time.zone.today.year
  = submit_tag 'Go'

= cache [Current.household, @period.first, @period.last] do
  #SpendingYear{
    data: {
      controller: 'spending-graph',
      spending_graph_expense_value: @period.step(7).collect{|date| Current.household.sum_expenses(@period.first..date) * -1},
      spending_graph_income_value: @period.step(7).collect{|date| Current.household.sum_income @period.first..date},
      spending_graph_start_year_value: (@period.first - 1.month).year,
      spending_graph_start_month_value: (@period.first - 1.month).month,
      spending_graph_start_day_value: (@period.first - 1.month).day
    }
  }

%table
  %tr
    %td{colspan: 2} All
  %tr
    %td Income
    %td= color_money @income
  %tr
    %td Expenses
    %td= color_money @expenses
  %tr
    %td Net
    %td= color_money @net
  - unless @income.zero?
    %tr
      %td Savings Rate
      %td #{(@net / @income.to_f * 100).round(1)}%

  %tr
    %td{colspan: 2} Non-Exceptional Cash
    %tr
      %td Income
      %td= color_money @exceptional_income
    %tr
      %td Expenses
      %td= color_money @exceptional_expenses
    %tr
      %td Net
      %td= color_money @exceptional_net
    - unless @exceptional_income.zero?
      %tr
        %td Savings Rate
        %td #{(@exceptional_net / @exceptional_income.to_f * 100).round(1)}%

%h2 Top Expenses
%table
  %tr
    %th Account
    %th Biweekly
    %th Annual
    %th Transactions
    %th Total
  - @expense_accounts.each do |account|
    - non_exceptional_total = @non_exceptional_account_totals[account.id] || 0
    %tr
      %td= account.name
      %td.count= color_money((non_exceptional_total / @duration) * 15 * -1)
      %td.count= color_money((non_exceptional_total / @duration) * 365 * -1)
      %td.count= account.transaction_count
      %td.count= color_money(account.total * -1)

%table
  %tr
    %th Account
    %th Biweekly
    %th Annual
    %th Transactions
    %th Total
  - @expense_tags.each do |tag|
    - non_exceptional_total = @non_exceptional_tag_totals[tag.id] || 0
    %tr
      %td= tag.name
      %td.count= color_money((non_exceptional_total / @duration) * 15 * -1)
      %td.count= color_money((non_exceptional_total / @duration) * 365 * -1)
      %td.count= tag.transaction_count
      %td.count= color_money(tag.total * -1)